### PR TITLE
Fixes for IE11

### PR DESCRIPTION
**Pull request by henryjameslau**
Added in a few fixes for IE11
- polyfill for Object.assign and string.includes
- CSS for IE11 needs quotes around for animation-name

Tested on IE11.0.9600.19236

### CODE REVIEW

**Comment by dmitrizzle** [comment]
Hey @henryjameslau, thanks for the PR!

I'm not sure polyfilling browsers is what this tool should do. I think it's up to the developer to add them on top of the package if they wish to support older browsers (some won't).

I suggest you add those polyfills somewhere before the Bubbles.js code runs in your application. We can add this to docs if you feel it's important, to show users how to do this.

However, I am fine with CSS fix for IE11 as it's very small change. Can you confirm that it doesn't break the rest of the browsers though?

**Comment by henryjameslau** [comment]
Hi,
Fair point about the polyfill, I think linking to the necessary polyfills for IE in the docs would be great.

Have checked the CSS fix and it doesn't break Firefox 65 or Chrome 70.

**Comment by dmitrizzle** [comment]
Thank you. Would you mind adjusting your PR to clear the polyfill? I recommend you create a GIST for the polyfills and we can link it form the docs. Or, feel free to edit the docs to add the info. @henryjameslau

**Comment by henryjameslau** [comment]
@dmitrizzle Done. Removed the polyfills and included some links in the readme for them.

**Comment by dmitrizzle** [comment]
Perfect, thank you. Will run a release tonight or tomorrow 👍

**Pull request merged**
